# Generated by Django 4.2.13 on 2024-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_adminstrator_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                    ("adminstrator", "Adminstrator"),
                ],
                max_length=12,
            ),
        ),
    ]
