# Generated by Django 4.2.13 on 2024-05-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_userprofile_role"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Adminstrator",
            new_name="Administrator",
        ),
    ]
